resolve many bugs and update all branches
zimb0o/capstone-project pull request #15
Opened 2023-05-19 11:01 UTC by zimb0o

I had to create this branch in order to update all my components to the latest version and continue working properly. With this state, I can properly work on all future features/branches.

2023-05-19 13:45 UTC, mbosselmann reviewed
Hi Alex,
good job! 👍 I left some remarks for you to consider before moving further. :)

2023-05-19 13:45 UTC, mbosselmann commented on components/Header.js
> +  let title = setTitle();
I think you can also work with `const`:)

2023-05-19 13:45 UTC, mbosselmann commented on components/Header.js
> +  font-size: 18px;
I recommend to not work with `px` for `font-size` for accessibility reasons. [See this article for more information.](https://www.joshwcomeau.com/css/surprising-truth-about-pixels-and-accessibility/#accessibility-considerations-5)

2023-05-19 13:45 UTC, mbosselmann commented on components/Layout.js
> +export default function Layout({ pageTitle, children }) {
You do not use the prop `pageTitle`. This can be removed. :)

2023-05-19 13:45 UTC, mbosselmann commented on components/SpotCard.js
> +        <Name>{spot?.Spotname}</Name>
`spot.spotname` is a bit redundant. `spot.name` is sufficient enough

2023-05-19 13:45 UTC, mbosselmann commented on components/SpotDetails.js
> +          ))}
It is better to work with a unique id than with an `index`. [See this article to learn about the usage of keys in React.](https://react.dev/learn/rendering-lists#keeping-list-items-in-order-with-key)

2023-05-19 13:45 UTC, mbosselmann commented on components/SpotDetails.js
> +            <li key={index}>{item}</li>
Same here for key as mentioned above.

2023-05-19 13:45 UTC, mbosselmann commented on components/SpotForm.js
> +      Tasks: formData.Tasks, // Updated property name
I think the comments are redundant or?

2023-05-19 13:45 UTC, mbosselmann commented on helpers/localStorage.js
> +
Why did you choose to use this local storage hook and did not work with `local-storage-state`? ([See handout for the local storage session) ](https://github.com/neuefische/web-muc-23-1/blob/main/sessions/react-with-local-storage/react-with-local-storage.md#react-with-local-storage-1)🤔

2023-05-19 13:45 UTC, mbosselmann commented on components/SpotForm.js
> +    addSpot(newSpot);
```suggestion
    const updatedSpots = [...existingSpots, newSpot];
    addSpot(newSpot);
```
- you already update the spot data in your local storage with addSpot :)

2023-05-19 13:45 UTC, mbosselmann commented on components/SpotForm.js
> +    console.log(formData);
console.logs can be removed :)

2023-05-19 13:45 UTC, mbosselmann commented on components/SpotForm.js
> +        </FormGroup>
```suggestion
        <fieldset>
          <legend>Tasks:</legend>
          {formTaskOptions.map((option) => (
            <FormLabel key={option}>
              <FormInput
                type="checkbox"
                checked={formData.Tasks.includes(option)}
                onChange={() => handleOptionToggle(option, "Tasks")}
              />
              {option}
            </FormLabel>
          ))}
        </fieldset>
```
It is better to group your form with fieldset and legend. [See MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset)

2023-05-19 13:45 UTC, mbosselmann commented on components/SpotForm.js
> +        </FormGroup>
Same here for this form group

2023-05-19 13:45 UTC, mbosselmann commented on components/SpotForm.js
> +        <Button type="submit">Submit</Button>{" "}
The space is not needed or?

2023-05-19 13:45 UTC, mbosselmann commented on pages/_app.js
> +    console.log(spots);
This console.log should also be removed. :)

2023-05-19 13:45 UTC, mbosselmann commented on pages/_app.js
> +        setSpots={addSpotHandler}
For less confusing when handling your props I would recommend to use the name `addSpotHandler` and not `setSpots`

2023-05-19 13:45 UTC, mbosselmann commented on pages/create/index.js
> +      {" "}
The space is not needed. :)

2023-05-21 14:20 UTC, zimb0o commented
I have a small bug with the addspots function that I can't fix.

2023-05-22 11:39 UTC, zimb0o commented
have a small bug with the addspots function that I can't fix.

2023-05-22 12:50 UTC, ThomasKirst requested changes
Hi Alex,
I found a few minor issues and left you some comments.
If you have any questions feel free to reach out and ask.
– Thomas

2023-05-22 12:50 UTC, ThomasKirst commented on components/SpotCard.js
> +          equipment={spot?.Equipment}
This is ok, but it would be considered common practice to name object properties lowercase, as such:
```js
<SpotDetails
          name={spot?.name}
          address={spot?.address}
          tasks={spot?.tasks}
          equipment={spot?.equipment}
```

2023-05-22 12:50 UTC, ThomasKirst commented on components/SpotForm.js
> +      Equipment: formData.Equipment,
As mentioned earlier, I would prefer the object properties lowercase.

2023-05-22 12:50 UTC, ThomasKirst commented on components/SpotForm.js
> +      id: formData.id,
This would be the right spot to call the `uuidv4` function to generate the `id`.

2023-05-22 12:50 UTC, ThomasKirst commented on components/SpotForm.js
> +    localStorage.setItem("spots", JSON.stringify(updatedSpots));
You have included a localStorage hook already – why don´t you use it here?

2023-05-22 12:50 UTC, ThomasKirst commented on components/SpotForm.js
> +    addSpots(newSpot);
```suggestion
    addSpot(newSpot);
```
I would call this function as I saw it before:  `addSpot`, since you just add _one_ spot.

2023-05-22 12:50 UTC, ThomasKirst commented on components/SpotForm.js
> +  margin-bottom: 1 rem;
```suggestion
  margin-bottom: 1rem;
```

2023-05-22 12:50 UTC, ThomasKirst commented on pages/_app.js
> +  const [spots, addSpots] = useLocalStorage("spots", mockSpots);
To be consistent with state setter actions, I would call it `setSpots` here, as you had it before.

2023-05-22 12:50 UTC, ThomasKirst commented on pages/_app.js
> +    addSpots(newSpotArray);
This would remain `setSpots`.

2023-05-22 12:50 UTC, ThomasKirst commented on pages/create/index.js
> +export default function CreateSpot({ addSpots }) {
Did you mean to receive `addSpotHandler` here?

2023-05-22 12:50 UTC, ThomasKirst commented on pages/create/index.js
> +  }
Not sure, if you then still need this function, as you could just pass `addSpotHandler` along to the `SpotForm` component.

2023-05-22 12:50 UTC, ThomasKirst commented on pages/spots/index.js
> +    <Layout pageTitle="Spots">
This is cool! You almost had it 😅 You need to pass along the `pageTitle` property in your `Layout` component.

```js
// Layout
export default function Layout({ pageTitle, children }) {
  return (
    <>
      <Header pageTitle={pageTitle} />
      <main>{children}</main>
      <Footer />
    </>
  );
}

// Header
export default function Header({ pageTitle }) {
  return (
    <StyledHeader>
      <Headline>{pageTitle}</Headline>
    </StyledHeader>
  );
}
```

Then you won´t need this part
```js
const { pathname } = useRouter();

  function setTitle() {
    switch (pathname) {
      case "/spots":
        return "Spots";
      case "/create":
        return "add your Spot";
      case "/favorites":
        return "Favorites";
    }
  }
  const title = setTitle();
```

2023-05-22 12:57 UTC, ThomasKirst commented on components/SpotDetails.js
> +            <li key={equipment.id}>{item}</li>
This can´t be right, I suggest you just use the item as the key here.

2023-05-22 12:59 UTC, ThomasKirst commented on components/SpotForm.js
> +            <FormLabel key={task.id}>
Just use the task itself for the key if you don´t have an id.
The same should be applied to the equipments (line 109).

2023-05-22 14:42 UTC, ThomasKirst commented on components/SpotForm.js
>        Equipment: [],
You renamed the object properties –> Good!
Then you should also rename the form fields (lowercase).

2023-05-22 14:53 UTC, doctype-Melvin reviewed
Hey Alex!
You're putting in the work. I like that. 
Just left you one small remark.

2023-05-22 14:53 UTC, doctype-Melvin commented on components/SpotCard.js
> +          name={spot?.Name}
Is this supposed to be `name={spot?.name}` ?

2023-05-24 12:12 UTC, merged